-- TODO: Colocate theme configs
-- TODO: Figure out a way to have a dynamic highlight color based on the current highlight
-- TODO: Figure out a way to set the globals here and reload the plugin, or not use globals at all
--vim.g.qs_highlight_on_keys = { "f", "F", "t", "T" }
-- The highlight background color should stand out from the rest of the
-- text; we are underlining it in the theme setup
